### ISSUE TITLE
Detect projectId and locationId automatically

### ISSUE THREAD

**Issue by wereHamster** [googleapis/nodejs-scheduler#179]
The API as it is is not very convenient to use. I have to supply the projectId and locationId to many functions. Ideally the library would automatically detect them when possible (using application default credentials for example).

I know I can get the projectId using `client.getProjectId()`, but that function is async so it's not possible to use it in module top-level scope for example. I have not found a way to get the locationId.

Furthermore, it appears that locationId can only be "europe-west1" and "us-central1", and must match the AppEngine location. I received the following error: "INVALID_ARGUMENT: Location must equal us-central1 because the App Engine app that is associated with this project is located in us-central1". Instead of throwing an error, it would be nice if the library could automatically derive it from the project's AppEngine location. I'm sure there is an API to get the AppEngine location of a particular project (given a projectId).

For comparison, consider the PubSub API. When running inside a Google Cloud Function (Firebase Function, actually), the following works out of the box:

```
const { PubSub } = require("@google-cloud/pubsub");
(new PubSub()).topic("some-topic").publishJSON({ … })
```

An analogous Cloud Scheduler API could look like this for example:

```
const { CloudSchedulerClient } = require("@google-cloud/scheduler");
client.resumeJob({ name: "JOB_ID" })
client.resumeJob({ path: "projects/PROJECT_ID/locations/LOCATION_ID/jobs/JOB_ID" });
```

**Comment by stephenplusplus** [comment]
@alexander-fenster we have the path-building helpers, right? Is it possible there's more autocompleting we could do on the user's behalf?

**Comment by wereHamster** [comment]
Inside a Firebase Function one can access the location through, it's a workaround I'm using for the time being:

```
JSON.parse(process.env.FIREBASE_CONFIG).locationId
```

The full code looks something like this:

```
const client = new CloudSchedulerClient();
const projectId = await client.getProjectId();

const name = client.jobPath(
  projectId,
  JSON.parse(process.env.FIREBASE_CONFIG).locationId,
  `firebase-schedule-triggerImport-${region}`
);

client.pauseJob({ name });
```

**Comment by radvansky-tomas** [comment]
Any update on this ? 
`JSON.parse(process.env.FIREBASE_CONFIG).locationId`

Is still invalid...it should return actual location **us-central1**

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue is still persisting, please feel free to reopen there. Thank you!
