### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-scheduler#18]
The README link in the sentence 
>The Cloud Scheduler Node.js Client API Reference documentation also contains samples
leads to a 404.

https://cloud.google.com/nodejs/docs/reference/scheduler/latest/

**Comment by JustinBeckwith** [comment]
@kinwa91 can you publish these today?

**Comment by averikitsch** [comment]
@kinwa91 ping

**Comment by kinwa91** [comment]
Thanks for the report - we've since published the docs!
