### ISSUE TITLE
Auth is not compatible with google-api-nodejs library

### ISSUE THREAD

**Issue by evil-shrike** [googleapis/nodejs-scheduler#346]
If I set up globally auth with [google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client/):
```
  const auth = await new google.auth.GoogleAuth({
    keyFile: keyFile,
    scopes: OAUTH_SCOPES
  });
  google.options({
    auth: auth
  });
```
it'll be used by all API clients in google-api-nodejs-client, but this lib ignores the settings.
Even when I tried to explicitly set auth it complains about incompatible interfaces (I use TypeScript):
```
  let schedulerClient = new Scheduler.CloudSchedulerClient({auth: <GoogleAuth>google._options.auth});
```
error: Type 'GoogleAuth' is missing the following properties from type 'GoogleAuth': getAnyScopes, getExternalAccountClientProjectId

So how are these two libs supposed to be used together?

I understand I can use Scheduler client from google-api-nodejs-client but in docs it's stated that this one is the recommended way. google-api-nodejs-client is inevitable as well, as lots of APIs don't have new modular clients.

**Comment by averikitsch** [comment]
This client does not have an `auth` field. The [documentation](https://googleapis.dev/nodejs/scheduler/latest/v1.CloudSchedulerClient.html) shows the ability to use fields like `credentials` and `keyFilename`. Specifying auth shouldn't be necessary if running on GCP like App Engine or Cloud Run and locally it would look for credentials via env var `$GOOGLE_APPLICATION_CREDENTIALS`. The `google-api-nodejs-client` auth library is meant to work with the googleapis libraries not the recommended google-cloud-node libraries.

**Comment by evil-shrike** [comment]
Averi, thanks for the response, I understand all that but despite cases when code is being executed in GCP with application default credentials and everything just works there're cases when we need to specify auth explicitly. 
Thankfully all clients from google-api-nodejs-client lib integrates nicely with [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs/) to support the global auth options. It's super useful. 

And I would expect that the new Cloud idiomatic client libs continue to support that pattern. Because if my project uses several Google APIs and I have to mix google-api-nodejs-client and @google-cloud/* libs (such as this one for Scheduler), I'd have to define auth in two different ways which would be inconvenient. 
Unfortunately the new client libs work a bit different. They (at least this one) do support passing GoogleAuth object in auth option (see below) but ignore the global options in `google.options`. The later is quite understandable as this `google.options` object is coming from googleapis and not google-auth-library. 

> This client does not have an auth field.

Maybe it doesn't exist in docs but  in code CloudSchedulerClient's constructor accepts `ClientOptions` from google-gax which extends `GoogleAuthOptions` from google-auth-library-nodejs.
The problem I encountered was due to the usage of different versions of google-auth-library-nodejs that googleapis and "@google-cloud/scheduler" depended upon. As soon as I removed explicitly installed google-auth-library-nodejs@7.0.4 and updated googleapis and "@google-cloud/scheduler" to their latest versions (which depends on google-auth-library-
nodejs@7.0.2) everything has started working as expected:

```ts
import Scheduler from '@google-cloud/scheduler';
import { GoogleAuth } from 'google-auth-library';
import { google } from 'googleapis';

async function main() {
  let keyFile = './keys/my-project-sa.json';
  const auth = await new google.auth.GoogleAuth({
    keyFile: keyFile,
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  });
  google.options({
    auth: auth  // this settings is ignored
  });

  let s = new Scheduler.CloudSchedulerClient({auth: auth});  // passing auth works
  let parent = `projects/my-project/locations/europe-west1`;
  let jobs = (await s.listJobs({parent}));
  console.log(jobs);
}

main().catch(console.error);
```

So the main my claim that auth is not compatible isn't correct, they do. And the only suggestion, I'd say, it to support the global auth options in `google.options.auth`. But I'm not sure where exactly it should be...

**Comment by averikitsch** [comment]
@googleapis/yoshi-nodejs can you PTAL

**Comment by JustinBeckwith** [comment]
Greetings!  I wonder if all of this is maybe caused by the `await` in `const auth = await new google.auth.GoogleAuth({`?  That's not needed!  I was able to get this all working with this code:

```ts
import {GoogleAuth} from 'google-auth-library';
import {google} from 'googleapis';
import {CloudSchedulerClient} from '@google-cloud/scheduler';

const auth = new GoogleAuth();
google.options({auth});

async function main() {
  const projectId = await auth.getProjectId();
  const location = 'us-central1';
  const discoScheduler = google.cloudscheduler('v1');
  const list1 = await discoScheduler.projects.locations.jobs.list({
    parent: `projects/${projectId}/locations/${location}`,
  });
  console.log(list1.data.jobs);

  const gapicScheduler = new CloudSchedulerClient({auth});
  const [list2] = await gapicScheduler.listJobs({
    parent: gapicScheduler.locationPath(projectId, location),
  });
  console.log(list2);
}
main();
```

I have the following dependencies and versions in my package.json:
```json
"dependencies": {
    "@google-cloud/scheduler": "^2.2.0",
    "google-auth-library": "^7.0.4",
    "googleapis": "^71.0.0"
  }
```

You should absolutely be able to instantiate a new `GoogleAuth` client once, and re-use it between both the discovery based clients (googleapis) and the GAPIC based clients. 


On supporting a global auth option broadly in the new libraries - we are very much moving *away* from this pattern.  Even the `googleapis` package is going to get split up, and you will have to attach that auth object to each client.  For your usage, if you're relying on application default credentials, you may not need to do anything.  

It seems like from your last message you're all set here.  Is there anything currently busted/not-working we can help with?

**Comment by evil-shrike** [comment]
Hi Justin, thanks for looking into it. 
If supporting global options was removed/not implemented on purpose then there's no any other complain
(in your code you set auth explicitly in the client and I believe that if you remove it, then will notice that `google.options({auth})` isn't  used)
