### ISSUE TITLE
3 INVALID_ARGUMENT: Invalid mask for Job: timeZone

### ISSUE THREAD

**Issue by MTA1711** [googleapis/nodejs-scheduler#447]
Hello I'm trying to use the lib to update a job timezone. I updated the sample code for job update with timezone information
but I have an error `3 INVALID_ARGUMENT: Invalid mask for Job: timeZone`

#### Environment details

  - OS: Windows 10
  - Node.js version:  v14.18.1
  - npm version: 6.14.15
  - `@google-cloud/scheduler` version: 2.3.0

Thanks!

**Comment by averikitsch** [comment]
Hi @MTA1711 , field names must be convert to lower camel ie `time_zone`. I am updating the example here https://github.com/googleapis/nodejs-scheduler/pull/449/files
