### ISSUE TITLE
docs: write code samples for using v1 API

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-scheduler#60]
## Problem

We just pulled in version 1 of the scheduler API [here](https://github.com/googleapis/nodejs-scheduler/pull/59), there is however no documentation on how one might use this new API.

## Solution

Let's write a code sample of using the version 1 API, we might need to update the README as well.

## Alternative Solution

Perhaps we could get away with just updating the README?

**Comment by JustinBeckwith** [comment]
So ... good news!  The samples,  as written today, *are* using `v1` of the API :)  When you don't specify a sub-version, it, it just takes the latest by default.  If I'm missing something though... do let me know!
