### ISSUE TITLE
Add an example of updateMask

### ISSUE THREAD

**Issue by simonebracaloni** [googleapis/nodejs-scheduler#64]
### Problem

I spent a lot of time figuring out how to pass updateMask in plain JS

### Solution

It would be very useful to update the documentation of updateJobs with a filled updateMask example like:
```
const job = {
        name,
        description,
        schedule
    };
const updateMask = {
    paths: ["description","schedule"]
};
const request = {
    job,
    updateMask
};
```

### Alternative solution

As this actually applies to all the JS libraries backed by grpc this documentation may be added somewhere else.

**Comment by averikitsch** [comment]
Fixed in #265
